
package Schermen;

import Gebruikers.Treinkoerier;
import Pakketten.Pakket;
import javax.swing.*;

/**
 *
 * @author Olink
 */
public class Status_pakket_scherm extends javax.swing.JFrame {
    private String gebruikersnaam;

    /**
     * Creates new form Status_pakket_scherm
     */
    public Status_pakket_scherm(String gebruikersnaam) {
        initComponents();
        
        this.gebruikersnaam = gebruikersnaam;
        
        Pakket p = new Pakket(this.gebruikersnaam);
        
        //Set de texten en radiobuttons op de juiste wijze van pakketID
        this.jpakketid.setText("Status pakket #" + p.getPakketId());
        this.jkoerier.setText("Koerier: " + p.getGebruikersnaam());
        this.jafgeleverdbutton.setSelected(p.getAfgeleverd());
        this.jopgehaaldbutton.setSelected(p.getOpgehaald());
        this.jbincident.setSelected(p.getIncident());
        
        this.jwijzigingopgeslagen.setVisible(false);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpakketid = new javax.swing.JLabel();
        jkoerier = new javax.swing.JLabel();
        jopgehaald = new javax.swing.JLabel();
        jafgeleverd = new javax.swing.JLabel();
        jopgehaaldbutton = new javax.swing.JRadioButton();
        jafgeleverdbutton = new javax.swing.JRadioButton();
        jincident = new javax.swing.JLabel();
        jbincident = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jstatus_beschrijving = new javax.swing.JTextArea();
        jbopslaan = new javax.swing.JButton();
        jbterug = new javax.swing.JButton();
        jwijzigingopgeslagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpakketid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jpakketid.setText("jpakketid");

        jkoerier.setText("jkoerier");

        jopgehaald.setText("Opgehaald:");

        jafgeleverd.setText("Afgeleverd:");

        buttonGroup1.add(jopgehaaldbutton);
        jopgehaaldbutton.setToolTipText("");
        jopgehaaldbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jafgeleverdbutton);

        jincident.setText("Incident");
        jincident.setToolTipText("");

        buttonGroup1.add(jbincident);
        jbincident.setToolTipText("");

        jstatus_beschrijving.setColumns(20);
        jstatus_beschrijving.setRows(5);
        jstatus_beschrijving.setText("beschrijving...");
        jstatus_beschrijving.setToolTipText("");
        jScrollPane1.setViewportView(jstatus_beschrijving);

        jbopslaan.setText("Opslaan");
        jbopslaan.setToolTipText("");
        jbopslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbopslaanActionPerformed(evt);
            }
        });

        jbterug.setText("Terug");
        jbterug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbterugActionPerformed(evt);
            }
        });

        jwijzigingopgeslagen.setForeground(new java.awt.Color(255, 51, 51));
        jwijzigingopgeslagen.setText("Wijzigingen zijn  opgeslagen!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jkoerier)
                            .addComponent(jpakketid)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jopgehaald, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jafgeleverd)
                                    .addComponent(jincident))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jafgeleverdbutton)
                                    .addComponent(jopgehaaldbutton)
                                    .addComponent(jbincident)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jbopslaan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jwijzigingopgeslagen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbterug))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jpakketid)
                .addGap(44, 44, 44)
                .addComponent(jkoerier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jopgehaald, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jopgehaaldbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jafgeleverd)
                    .addComponent(jafgeleverdbutton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jincident)
                    .addComponent(jbincident))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbopslaan)
                    .addComponent(jbterug)
                    .addComponent(jwijzigingopgeslagen))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbopslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbopslaanActionPerformed
        //Updaten pakket's informatie gebasseerd op de aangevinkte radiobuttons
        Pakket p = new Pakket(this.gebruikersnaam);
        if (this.jopgehaaldbutton.isSelected()) {
            p.updatePakket(gebruikersnaam, "opgehaald");
            this.jwijzigingopgeslagen.setVisible(true);
        }
        if (this.jafgeleverdbutton.isSelected()) {
            p.updatePakket(gebruikersnaam, "afgeleverd");
            this.jwijzigingopgeslagen.setVisible(true);
        }
        if (this.jbincident.isSelected()) {
            p.updatePakket(gebruikersnaam, "incident", this.jstatus_beschrijving.getText());
            this.jwijzigingopgeslagen.setVisible(true);
        }
    }//GEN-LAST:event_jbopslaanActionPerformed

    private void jbterugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbterugActionPerformed
        Treinkoerierdashboard tkdb = new Treinkoerierdashboard(this.gebruikersnaam);
        this.setVisible(false);
    }//GEN-LAST:event_jbterugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status_pakket_scherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status_pakket_scherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status_pakket_scherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status_pakket_scherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jafgeleverd;
    private javax.swing.JRadioButton jafgeleverdbutton;
    private javax.swing.JRadioButton jbincident;
    private javax.swing.JButton jbopslaan;
    private javax.swing.JButton jbterug;
    private javax.swing.JLabel jincident;
    private javax.swing.JLabel jkoerier;
    private javax.swing.JLabel jopgehaald;
    private javax.swing.JRadioButton jopgehaaldbutton;
    private javax.swing.JLabel jpakketid;
    private javax.swing.JTextArea jstatus_beschrijving;
    private javax.swing.JLabel jwijzigingopgeslagen;
    // End of variables declaration//GEN-END:variables
}
